services:
#    pr2_l_user.example:
#        class: PR2L\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    pr2l_user.manager:
        class: PR2L\UserBundle\Utility\UserManager
