pr2_lsite:
    resource: "@PR2LsiteBundle/Resources/config/routing.yml"
    prefix:   /

pr2_l_article:
    resource: "@PR2LArticleBundle/Resources/config/routing.yml"
    prefix:   /publication #Toutes les routes du ArticleBundle

pr2_l_menu:
    resource: "@PR2LMenuBundle/Resources/config/routing.yml"
    prefix:   /

pr2_l_user:
    resource: "@PR2LUserBundle/Resources/config/routing.yml"
    prefix:   /user #TOUTES les routes du UserBundle commenceront par /user

#Accueil du site.
#pr2l_accueil:
#    defaults: {::base.html.twig}
#    path: /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
