pr2_l_article:
    resource: "@PR2LArticleBundle/Resources/config/routing.yml"
    prefix:   /

pr2_l_menu:
    resource: "@PR2LMenuBundle/Resources/config/routing.yml"
    prefix:   /

pr2_l_user:
    resource: "@PR2LUserBundle/Resources/config/routing.yml"
    prefix:   /user #TOUTES les routes du UserBundle commenceront par /user

#Accueil du site.
pr2l_accueil:
    defaults: {::base.html.twig}
    path: /
    
#pr2l__user_add:
#    path: /add
#    defaults: {_controller: PR2LUserBundle:Profil:add }

#app:
#    resource: @AppBundle/Controller/
#    type:     annotation
