pr2_l_user:
    resource: "@PR2LUserBundle/Resources/config/routing.yml"
    prefix:   /user #TOUTES les routes du UserBundle commenceront par /user

#app:
#    resource: @AppBundle/Controller/
#    type:     annotation
