<?php

namespace PR2L\SiteBundle\Entity\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * menuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class menuRepository extends EntityRepository
{
}
