<?php

namespace PR2L\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateurRepository extends EntityRepository
{
	public function myFindAll()
	{
		$qb = $this->_em->createQueryBuilder()
		  ->select('a')
		  ->from($this->_entityName, 'a')
		;

		return $qb
    		->getQuery()
    		->getResult()
  		;
	}
	
	public function myFindByLogin($login)
    {
        $qb = $this->createQueryBuilder('a');

  		$qb->where('a.username = :login')
       		->setParameter('login', $login)
  		;

 		return $qb
    		->getQuery()
    		->getResult()
  		;
    }
}
