# app/config/routing.yml

pr2_l_site:
    resource: "@PR2LSiteBundle/Resources/config/routing.yml"
    prefix:   /pr2l/

login:
    pattern:   /pr2l/login
    defaults:  { _controller: PR2LUserBundle:Security:login }

login_check:
    pattern:   /pr2l/login_check

logout:
    pattern:   /pr2l/logout

pr2_l_archives:
    resource: "@PR2LArchivesBundle/Resources/config/routing.yml"
    prefix:   /pr2l/
