<?php

namespace PR2L\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends EntityRepository
{
	public function whereLoginAndPwdAre($login, $pwd)
	{
		$qb = $this->createQueryBuilder('p');
	
		$qb->where('p.userLogin = :login')
		->setParameter('login', $login)
		->andWhere('p.userPwd = :year')
		->setParameter('year', $pwd)
		;
	
		return $qb
		->getQuery()
		->getResult()
		;
	}
}
