<?php

namespace PR2L\ArchivesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * archiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class archiveRepository extends EntityRepository
{
    public function myFindAll(){
        return $this->createQueryBuilder('a')->getQuery()->getResult();
    }
    
    public function myFindById($id){
        $qb = $this->createQueryBuilder('a');
        
        $qb->where('a.id = :identifiant')
           ->setParameter('identifiant', $id);
        
        return $qb
                ->getQuery()
                ->getResult();
    }
    
    public function myFindByAuteur($auteur){
        $qb = $this->createQueryBuilder('a');
        
        $qb->where('a.producteurArchive = :auteur')
           ->setParameter('auteur', $auteur);
        
        return $qb
                ->getQuery()
                ->getResult();
    }
    
    public function myFindArchive($auteur,$departement,$fond){
        $qb = $this->createQueryBuilder('a');
        
        if($fond != null){
            $qb ->where('a.nomDuFond = :fond')
                ->setParameter('fond', $fond);
        }
        if($departement != null){
            $qb ->where('a.departementDuFond = :departement')
                ->setParameter('departement', $departement);
        }
        if($auteur != null){
            $qb ->where('a.producteurArchive = :auteur')
                ->setParameter('auteur', $auteur);
        }
        
        return $qb
                ->getQuery()
                ->getResult();
    }
}
