<?php

namespace PR2L\ArchivesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tagsRepository extends EntityRepository
{
}
