<?php

namespace PR2L\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function myFindByType($type)
    {
        $qb = $this->createQueryBuilder('a');

  		$qb->where('a.type = :type')
       		->setParameter('type', $type)
  		;

 		return $qb
    		->getQuery()
    		->getResult()
  		;
    }
    
    public function valider($id){
        $query = $this->getEntityManager()
        ->createQuery('
            UPDATE PR2L\SiteBundle\Entity\Document d
            SET d.valide = 1
            WHERE d.id = :identifiant'
        )->setParameter('identifiant', $id);

        $result = $query->getSingleResult();

    }
    
    public function invalider($id){
        $query = $this->getEntityManager()
        ->createQuery('
            UPDATE PR2L\SiteBundle\Entity\Document d
            SET d.valide = 0
            WHERE d.id = :identifiant'
        )->setParameter('identifiant', $id);

        $result = $query->getSingleResult();

    }
}
