<?php

namespace PR2L\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EssaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EssaiRepository extends EntityRepository
{
    $repository = $this
        ->getDoctrine()
        ->getManager()
        ->getRepository('PR2lSiteBundle:Entity')
        ;

    $listAdverts = $repository->findAll();

    foreach ($listAdverts as $advert) {
        // $advert est une instance de Advert
    echo $advert->getContent();
}
}
