<?php

namespace PR2L\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * menuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class menuRepository extends EntityRepository
{
	public function myFindByParent($parent)
	{
  		$qb = $this->createQueryBuilder('a');

  		$qb->where('a.idMenuParent = :parent')
       		->setParameter('parent', $parent)
  		;

 		return $qb
    		->getQuery()
    		->getResult()
  		;
	}
}
