<?php

namespace PR2L\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateurRepository extends EntityRepository
{
    public function myFindAll(){
        return $this->createQueryBuilder('a')->getQuery()->getResult();
    }
    
    public function myFindByLogin($login){
        $qb = $this->createQueryBuilder('a');
        
        $qb->where('a.login = :identifiant')
            ->setParameter('identifiant', $login);
        
        return $qb
                ->getQuery()
                ->getResult()
            ;
    }
}
