pr2_l_archives_archives:
    path:     /archives
    defaults: { _controller: PR2LArchivesBundle:Archives:archives }
    
pr2_l_archives_ajouter:
    path:     /ajouter
    defaults: { _controller: PR2LArchivesBundle:Ajouter:ajouter }
    
pr2_l_archives_rechercheAvancee:
    path:     /rechercheAvancee
    defaults: { _controller: PR2LArchivesBundle:RechercheAvancee:rechercheAvancee }
    
pr2_l_archives_detail:
    path:     /detail/{id}
    defaults: { _controller: PR2LArchivesBundle:Detail:detail, id: 1 }
    
pr2_l_archives_modifier:
    path:     /modifier
    defaults: { _controller: PR2LArchivesBundle:Modifier:modifier }
    
pr2_l_archives_tag:
    path:     /tag/{id}
    defaults: { _controller: PR2LArchivesBundle:Tag:tag, id: 1 }
    
pr2_l_archives_validation:
    path:     /validation
    defaults: { _controller: PR2LArchivesBundle:Validation:validation }
    
pr2_l_archives_valider:
    path:     /valider/{id}
    defaults: { _controller: PR2LArchivesBundle:Valider:valider, id: 1 }
    
pr2_l_archives_confirmation:
    path:     /confirmation/{id}
    defaults: { _controller: PR2LArchivesBundle:Valider:confirmation, id: 1 }