pr2_l_site_accueil:
    path:     /accueil
    defaults: { _controller: PR2LSiteBundle:Accueil:accueil }

pr2_l_site_actionsEvenements:
    path:     /actionsEvenements
    defaults: { _controller: PR2LSiteBundle:ActionsEvenements:actionsEvenements }
    
pr2_l_site_projet:
    path:     /projet
    defaults: { _controller: PR2LSiteBundle:Projet:projet }
    
pr2_l_site_fondateurs:
    path:     /fondateurs
    defaults: { _controller: PR2LSiteBundle:Fondateurs:fondateurs }
    
pr2_l_site_revuePresseAdd:
    path:     /revuePresse
    defaults: { _controller: PR2LSiteBundle:RevuePresse:add }
    
pr2_l_site_revuePresseEdit:
    pattern:  /revuePresse/{id}/edit
    defaults: { _controller: PR2LSiteBundle:RevuePresse:edit }
    requirements:
        id:  \d+

pr2_l_site_revuePresseDelete:
    pattern:  /revuePresse/{id}/delete/
    defaults: { _controller: PR2LSiteBundle:RevuePresse:delete }
    requirements:
        id:  \d+

pr2_l_site_adherer:
    path:     /adherer
    defaults: { _controller: PR2LSiteBundle:Adherer:adherer }
    
pr2_l_site_vieAssociation:
    path:     /vieAssociation
    defaults: { _controller: PR2LSiteBundle:VieAssociation:vieAssociation }
    
pr2_l_site_actualites:
    path:     /actualites
    defaults: { _controller: PR2LSiteBundle:Actualites:actualites }
    
pr2_l_site_quoiDeNeuf:
    path:     /quoiDeNeuf
    defaults: { _controller: PR2LSiteBundle:QuoiDeNeuf:quoiDeNeuf }
    
pr2_l_site_autourDeNous:
    path:     /autourDeNous
    defaults: { _controller: PR2LSiteBundle:AutourDeNous:autourDeNous }
    
pr2_l_site_partenaires:
    path:     /partenaires
    defaults: { _controller: PR2LSiteBundle:Partenaires:partenaires }
    
pr2_l_site_gererPartenaires:
    path:     /gererPartenaires
    defaults: { _controller: PR2LSiteBundle:GererPartenaires:gererPartenaires }
    
pr2_l_site_ressources:
    path:     /ressources
    defaults: { _controller: PR2LSiteBundle:Ressources:ressources }
    
pr2_l_site_bibliotheque:
    path:     /bibliotheque
    defaults: { _controller: PR2LSiteBundle:Bibliotheque:bibliotheque }
    
pr2_l_site_travauxRecherche:
    path:     /travauxRecherche
    defaults: { _controller: PR2LSiteBundle:TravauxRecherche:travauxRecherche }
    
pr2_l_site_publications:
    path:     /publications
    defaults: { _controller: PR2LSiteBundle:Publications:publications } 
        
pr2_l_site_liensUtiles:
    path:     /liensUtiles
    defaults: { _controller: PR2LSiteBundle:LiensUtiles:liensUtiles }     
    
pr2_l_site_chantiers:
    path:     /chantiers
    defaults: { _controller: PR2LSiteBundle:Chantiers:chantiers }  
    
pr2_l_site_inventaireCooperation:
    path:     /inventaireCooperation
    defaults: { _controller: PR2LSiteBundle:InventaireCooperation:inventaireCooperation } 
    
pr2_l_site_recensementMutualite:
    path:     /recensementMutualite
    defaults: { _controller: PR2LSiteBundle:RecensementMutualite:recensementMutualite }  
    
pr2_l_site_intranet:
    path:     /intranet
    defaults: { _controller: PR2LSiteBundle:Intranet:intranet }  
    
pr2_l_site_creation:
    path:     /creation
    defaults: { _controller: PR2LSiteBundle:Creation:creation }
    
pr2_l_site_gestionAdmin:
    path:     /gestionAdmin
    defaults: { _controller: PR2LSiteBundle:GestionAdmin:gestionAdmin }
    
pr2_l_site_modification:
    path:     /modification
    defaults: { _controller: PR2LSiteBundle:Modification:modification }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
