pr2_l_site_homepage:
    path:     /pr2l/accueil
    defaults: { _controller: PR2LSiteBundle:Default:accueil }

pr2_l_site_actionsEvenements:
    path:     /pr2l/actionsEvenements
    defaults: { _controller: PR2LSiteBundle:Default:actionsEvenements }
    
pr2_l_site_projet:
    path:     /pr2l/projet
    defaults: { _controller: PR2LSiteBundle:Default:projet }
    
pr2_l_site_projet:
    path:     /pr2l/fondateurs
    defaults: { _controller: PR2LSiteBundle:Default:fondateurs }