services:
#    pr2_l_site.example:
#        class: PR2L\SiteBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    pr2l_site.test:
        class: PR2L\SiteBundle\Tests\PR2LTest
        tags:
            - { name : twig.extension }
            
#    pr2l_site.essai:
#        class: PR2L\SiteBundle\Entity\EssaiRepository
#        tags:
#            - { name : twig.extension }